# Generated by Django 4.1.6 on 2023-02-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='total_sum',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
