# Generated by Django 4.1.6 on 2023-02-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patient_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pass_data',
            field=models.CharField(max_length=50),
        ),
    ]
